fail_fast: true
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)
        args: [--profile=black, --line-length=120]
  - repo: https://github.com/python/black
    rev: 21.9b0
    hooks:
      - id: black
        args: [--line-length=120]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [ flake8-bugbear, flake8-eradicate, pep8-naming, flake8-use-fstring, flake8-colors ]
        args: [--statistics]
