FROM quay.io/ocpmetal/assisted-service:latest AS service

FROM quay.io/app-sre/centos:8

RUN yum -y install make python3 libvirt-client libvirt-devel libguestfs-tools gcc unzip wget curl git python3-devel && yum clean all;

RUN wget -q https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_amd64.zip && unzip terraform*.zip -d /usr/bin/ && rm -rf terraform*.zip

RUN curl -Lo minikube https://storage.googleapis.com/minikube/releases/v1.10.1/minikube-linux-amd64 \
  && chmod +x minikube && mkdir -p /usr/local/bin/ && install minikube /usr/local/bin/
RUN curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/linux/amd64/kubectl && chmod +x kubectl && mv kubectl /usr/bin/

RUN mkdir -p /root/.terraform.d/plugins
RUN curl -SL https://github.com/dmacvicar/terraform-provider-libvirt/releases/download/v0.6.2/terraform-provider-libvirt-0.6.2+git.1585292411.8cbe9ad0.Fedora_28.x86_64.tar.gz | \
  tar -xz -C /root/.terraform.d/plugins

RUN curl -SL https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.6.0/openshift-client-linux-4.6.0.tar.gz | tar -xz -C /usr/bin

COPY requirements.txt /tmp/
COPY --from=service /clients/assisted-service-client-*.tar.gz /build/pip/
RUN pip3 install --no-cache-dir -r /tmp/requirements.txt && \
  pip3 install /build/pip/*

# TODO: Remove once OpenShift CI will be upgraded to 4.2 (see https://access.redhat.com/articles/4859371)
RUN chmod uga+w /etc/passwd

# setting pre-commit env
ENV PRE_COMMIT_HOME build
