FROM quay.io/edge-infrastructure/assisted-service:latest AS service

FROM quay.io/centos/centos:stream8

RUN dnf -y install \
  make \
  gcc \
  unzip \
  wget \
  curl \
  git \
  podman \
  httpd-tools \
  jq \
  nss_wrapper \
  python39 \
  python39-devel \
  libvirt-client \
  libvirt-devel \
  libguestfs-tools \
    && dnf config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo \
    && dnf -y install packer \
    && mv /usr/bin/packer /usr/bin/packer.io \
    && dnf -y install epel-release \
    && dnf -y install ansible \
    && dnf clean all

RUN curl -Lo terraform.zip https://releases.hashicorp.com/terraform/0.14.11/terraform_0.14.11_linux_amd64.zip && unzip terraform.zip -d /usr/bin/ && rm -rf terraform.zip
RUN curl -Lo - "https://github.com/vmware/govmomi/releases/latest/download/govc_$(uname -s)_$(uname -m).tar.gz" | tar -C /usr/local/bin -xvzf - govc

WORKDIR /home/assisted-test-infra

COPY requirements.txt requirements-dev.txt ./
COPY --from=service /clients/assisted-service-client-*.tar.gz /build/pip/
RUN pip3 install --upgrade pip && \
      pip3 install --no-cache-dir -I -r ./requirements.txt -r ./requirements-dev.txt && \
      pip3 install --upgrade /build/pip/*

RUN curl -s https://storage.googleapis.com/golang/go1.17.4.linux-amd64.tar.gz | tar -C /usr/local -xz
ENV GOPATH=/go
ENV GOCACHE=/go/.cache
ENV PATH=$PATH:/usr/local/go/bin:/go/bin

COPY . .

RUN chgrp -R 0 /home/assisted-test-infra && \
    chmod -R g=u /home/assisted-test-infra

# setting pre-commit env
ENV PRE_COMMIT_HOME build
