[tool.pyright]
extraPaths = [ "src" ]

[tool.black]
line-length = 120
target-version = ['py36']
include = '\.pyi?$'

[tool.isort]
multi_line_output = 3
line_length = 120
include_trailing_comma = true
