    - name: Download Metal cli
      ansible.builtin.get_url:
        url: "https://github.com/equinix/metal-cli/releases/download/v{{ metal_version }}/metal-linux-amd64"
        dest: /tmp/metal
        mode: '0775'
        checksum: "sha256:https://github.com/equinix/metal-cli/releases/download/v{{ metal_version }}/metal-cli_{{ metal_version }}_checksums.txt"
    
    - name: "Wait for plans to be available"
      shell:
        cmd: /tmp/metal capacity get -f  -P "{{ item }}"  | grep 'normal\|limited' | wc -l
      register: metal_cmd
      until: metal_cmd.stdout | int > 0
      retries: "{{ wait_retry_count }}"
      delay: "{{ wait_delay_seconds }}"
      environment:
        METAL_AUTH_TOKEN: "{{ equinix_auth_token }}"
      loop:
        - "{{ equinix_plans.primary }}"
        - "{{ equinix_plans.secondary }}"
