from .durations import HOUR, MINUTE


CRD_API_GROUP = 'agent-install.openshift.io'
CRD_API_VERSION = 'v1beta1'
HIVE_API_GROUP = 'hive.openshift.io'
HIVE_API_VERSION = 'v1'


DEFAULT_WAIT_FOR_CRD_STATUS_TIMEOUT = 5 * MINUTE
DEFAULT_WAIT_FOR_CRD_STATE_TIMEOUT = 5 * MINUTE
DEFAULT_WAIT_FOR_AGENTS_TIMEOUT = 5 * MINUTE
DEFAULT_WAIT_FOR_INSTALLATION_COMPLETE_TIMEOUT = 2 * HOUR
DEFAULT_WAIT_FOR_ISO_URL_TIMEOUT = 5 * MINUTE
DEFAULT_WAIT_FOR_KUBECONFIG_TIMEOUT = 5 * MINUTE
