---
- name: Enable IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: true

- name: Configure IPIP tunnel
  community.general.nmcli:
    type: ipip
    conn_name: "{{ ipip_connection_name }}"
    ifname: "{{ ipip_device_name }}"
    ip_tunnel_local: "{{ ipip_local_ipv4 }}"
    ip_tunnel_remote: "{{ ipip_remote_ipv4 }}"
    ip4: "{{ ipip_tunnel_ipv4 }}"
    routes4: "{{ ipip_route_to_network_ipv4 }} {{ ipip_tunnel_ipv4 | ansible.utils.ipaddr('peer') }}"
    autoconnect: true
    zone: "trusted"
    state: present
