---
- name: Generate an OpenSSH keypair
  community.crypto.openssh_keypair:
    path: "{{ shared_dir }}/{{ ssh_private_key_name }}"
    mode: "0600"
  delegate_to: localhost
  register: ssh_key_pair
  run_once: true

- name: Enable SHA1 algorithm
  ansible.builtin.command: "update-crypto-policies --set DEFAULT:SHA1"
  changed_when: false

- name: Ensure .ssh directory exists in user's home
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory
    mode: "0700"

- name: Set ssh settings as fact
  ansible.builtin.set_fact:
    ssh_private_key_path: "{{ ansible_user_dir }}/.ssh/{{ ssh_private_key_name }}"
    ssh_user: "{{ ansible_user_id }}"

- name: Copy private key to remote host
  ansible.builtin.copy:
    src: "{{ ssh_key_pair.filename }}"
    dest: "{{ ssh_private_key_path }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "0600"

- name: Authorize key
  ansible.posix.authorized_key:
    user: "{{ ansible_user_id }}"
    state: present
    key: "{{ ssh_key_pair.public_key }}"

- name: Create or update SSH client configuration
  ansible.builtin.blockinfile:
    block: "{{ lookup('template', 'config.j2') }}"
    path: "{{ ansible_user_dir }}/.ssh/config"
    create: true
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "0600"
