---
argument_specs:
  main:
    short_description: Release a CI resource back to OFCIR
    description:
      - This role releases a previously acquired CI resource back to OFCIR
      - It sends a DELETE request to the OFCIR API to free up the resource
    author: Assisted Test Infrastructure Team
    options:
      cir_name:
        description: Name of the CI resource to release
        type: str
        required: true
      ofcir_token:
        description: Authentication token for OFCIR API
        type: str
        required: true
        no_log: true
      ofcir_url:
        description: Base URL for the OFCIR API
        type: str
        required: true
      release_timeout_seconds:
        description: Timeout in seconds for the release request
        type: int
        default: 30
      request_retries:
        description: Number of retries for API requests
        type: int
        default: 60
      request_delay_seconds:
        description: Delay in seconds between retry attempts
        type: int
        default: 30
