---
argument_specs:
  main:
    short_description: Acquire a CI resource from OFCIR
    description:
      - This role acquires a CI resource from OFCIR (OpenShift Farm for CI Resources)
      - It polls the OFCIR API until a resource is provisioned and available
    options:
      cir_type:
        description: Type of CI resource to acquire
        type: str
        required: true
      cir_identifier:
        description: Unique identifier for the CI resource
        type: str
        required: true
      shared_dir:
        description: Directory path where CI resource information will be stored
        type: path
        required: true
      ofcir_token:
        description: Authentication token for OFCIR API
        type: str
        required: true
        no_log: true
      ofcir_url:
        description: Base URL for the OFCIR API
        type: str
        required: true
      acquire_timeout_seconds:
        description: Timeout in seconds for the initial acquisition request
        type: int
        default: 70
      request_retries:
        description: Number of retries for API requests
        type: int
        default: 60
      request_delay_seconds:
        description: Delay in seconds between retry attempts
        type: int
        default: 30
