---
- name: Validate Assisted Installer Deployment Environment
  hosts: assisted_installer
  roles:
  - okd.assisted_installer.validations
  tags:
  - validate
  - all

- name: Setup Assisted Installer infra Repository
  hosts: assisted_installer
  roles:
  - okd.assisted_installer.setup_repository
  tags:
  - setup_repo
  - all

- name: Creating Assisted Installer Discovery ISO
  hosts: assisted_installer
  roles:
  - okd.assisted_installer.create_iso
  tags:
  - create_iso
  - all

- name: Hosting Assisted Installer Discovery ISO
  hosts: assisted_installer
  roles:
  - okd.assisted_installer.host_iso
  tags:
  - host_iso
  - all
 
- name: Booting Assisted Installer Discovery ISO
  hosts: assisted_installer
  roles:
  - okd.assisted_installer.boot_iso
  tags:
  - boot_iso
  - all
