---
- name: Destroy equinix infrastructure
  hosts: localhost
  vars_prompt:
    - name: equinix_auth_token
      prompt: Equinix metal API token
    - name: equinix_tf_vars_file
      prompt: Terrafom variable file that was used to create the device(s)
      private: false
    - name: equinix_tf_state_file
      prompt: Terrafom state file that was used to create the device(s)
      private: false
  vars:
    terraform_equinix_workdir: "{{ playbook_dir }}/../terraform_files/equinix-ci-machine"
  roles:
    - equinix/generic_destroy_infra
