---
- name: Create and configure the CI machine on OCI
  hosts: localhost
  vars_prompt:
    - name: unique_id
      prompt: Unique ID used to name the resources
      private: false
    - name: oci_compartment_id
      prompt: parent compartment OCID where the resources will be created
      private: false
    - name: oci_tf_state_file
      prompt: Terrafom state file that was used to create the infrastructure
      private: false
    - name: oci_tf_vars_file
      prompt: Place where the Terrafom variable file will be stored
      private: false
    - name: oci_tenancy_id
      prompt: tenancy OCID authentication value
      private: false
    - name: oci_user_id
      prompt: user OCID authentication value
      private: false
    - name: oci_fingerprint
      prompt: key fingerprint authentication value
      private: false
    - name: oci_region
      prompt: OCI region
      private: false
    - name: oci_private_key_path
      prompt: private key path authentication value
      private: false
    - name: oci_private_ssh_key_path
      prompt: private SSH key path used to login the CI machine
      private: false
    - name: oci_public_ssh_key_path
      prompt: public SSH key path used to login the CI machine
      private: false
  vars:
    oci_terraform_workdir: "{{ [playbook_dir, '..', 'terraform_files', 'oci-ci-machine'] | path_join | realpath }}"
  roles:
    - role: oci_create_infra
      vars:
        private_ssh_key_path: "{{ oci_private_ssh_key_path }}"
        public_ssh_key_path: "{{ oci_public_ssh_key_path }}"
    - role: "oci_export_connection_details" # Export connection details, required for the "common" steps in Prow
    - role: "oci_setup_for_test_infra"
      vars:
        ci_machine: "{{ groups['primary'][0] }}"
