---
- name: Destroy infrastructure for heterogeneous cluster tests
  hosts: localhost
  vars_prompt:
    - name: "ofcir_url"
      prompt: "Enter the full URL for the OFCIR server API"
      private: false

    - name: "ofcir_token"
      prompt: "Enter your OFCIR API Token"
      private: true

    - name: "primary_cir_type"
      prompt: "Enter the primary CI resource type you want to request"
      private: false

    - name: "secondary_cir_type"
      prompt: "Enter the secondary CI resource type you want to request"
      private: false

    - name: "shared_dir"
      prompt: "Enter the local path to store the final resource files"
      private: false
      default: "/tmp"
  tasks:
    - name: Set CI resources to delete
      ansible.builtin.set_fact:
        ci_resources: >-
          {{
            {} |
            combine({primary_cir_identifier: primary_cir_type}) |
            combine({secondary_cir_identifier: secondary_cir_type})
          }}

    - name: Relase CI resources
      ansible.builtin.include_role:
        name: "heterogeneous_cluster_release_cir"
      vars:
        cir_type: "{{ item.value }}"
        cir_identifier: "{{ item.key }}"
      loop: "{{ ci_resources | dict2items }}"
