from consts import DISK_SIZE_100GB, GB, MiB_UNITS

DEFAULT_WORKER_MEMORY: int = 8 * MiB_UNITS
DEFAULT_MASTER_MEMORY: int = 16 * MiB_UNITS
DEFAULT_MTU: int = 1500
DEFAULT_WORKER_DISK: int = 20 * GB
DEFAULT_MASTER_DISK: int = DISK_SIZE_100GB
DEFAULT_DISK_COUNT: int = 1
DEFAULT_WORKER_CPU: int = 2
DEFAULT_MASTER_CPU: int = 4
DEFAULT_MASTER_SNO_MEMORY: int = 16 * MiB_UNITS
DEFAULT_MASTER_SNO_CPU: int = 8
