from consts import GB, MiB_UNITS

DEFAULT_WORKER_MEMORY: int = 8 * MiB_UNITS
DEFAULT_ARBITER_MEMORY: int = 8 * MiB_UNITS
DEFAULT_MASTER_MEMORY: int = 16 * MiB_UNITS
DEFAULT_MTU: int = 1500
DEFAULT_WORKER_DISK_GB: int = 20
DEFAULT_ARBITER_DISK_GB: int = 20
DEFAULT_MASTER_DISK_GB: int = 100
DEFAULT_WORKER_DISK: int = DEFAULT_WORKER_DISK_GB * GB
DEFAULT_ARBITER_DISK: int = DEFAULT_ARBITER_DISK_GB * GB
DEFAULT_MASTER_DISK: int = DEFAULT_MASTER_DISK_GB * GB
DEFAULT_DISK_COUNT: int = 1
DEFAULT_WORKER_CPU: int = 2
DEFAULT_ARBITER_CPU: int = 2
DEFAULT_MASTER_CPU: int = 4
DEFAULT_MASTER_SNO_MEMORY: int = 16 * MiB_UNITS
DEFAULT_MASTER_SNO_CPU: int = 8
