oci_compute_shape: "VM.Standard.E4.Flex"
oci_control_plane_shape: "VM.Standard.E4.Flex"

oci_infrastructure_zip_url: "https://github.com/dfoster-oracle/oci-openshift/releases/download/v1.0.0-preview/create-cluster-v0.1.0.zip"
oci_infrastructure_zip_file: "{{ hostvars[ci_machine].ansible_user_dir }}/oci/infrastructure.zip"
