argument_specs:
  main:
    short_description: Release CI resource by reading from stored file
    description:
      - This role reads a previously saved OFCIR resource file and releases the resource
      - It delegates to the ofcir/release role with the extracted resource name  
    author: Assisted Test Infrastructure Team
    options:
      cir_type:
        description: Type of CI resource to release
        type: str
        required: true
      cir_identifier:
        description: Unique identifier for the CI resource
        type: str
        required: true
      shared_dir:
        description: Directory path where CI resource information is stored
        type: path
        required: true
      ofcir_token:
        description: Authentication token for OFCIR API
        type: str
        required: true
        no_log: true
      ofcir_url:
        description: Base URL for the OFCIR API
        type: str
        required: true 
