---
argument_specs:
  main:
    short_description: Extract CI resource name from OFCIR response file
    description:
      - This role extracts the resource name from a previously saved OFCIR response file
      - It reads the JSON file and extracts the 'name' field for use in subsequent operations
    author: Assisted Test Infrastructure Team
    options:
      cir_type:
        description: Type of CI resource that was acquired
        type: str
        required: true
      cir_identifier:
        description: Unique identifier for the CI resource
        type: str
        required: true
      shared_dir:
        description: Directory path where CI resource information is stored
        type: path
        required: true
