import os

import consts

CLUSTER_INSTALLATION_TIMEOUT = (
    os.environ.get("CLUSTER_INSTALLATION_TIMEOUT")
    if os.environ.get("CLUSTER_INSTALLATION_TIMEOUT") is not None
    else consts.CLUSTER_INSTALLATION_TIMEOUT
)
CLUSTER_INSTALLATION_TIMEOUT_ODF = (
    os.environ.get("CLUSTER_INSTALLATION_TIMEOUT_ODF")
    if os.environ.get("CLUSTER_INSTALLATION_TIMEOUT_ODF") is not None
    else consts.CLUSTER_INSTALLATION_TIMEOUT_ODF
)
START_CLUSTER_INSTALLATION_TIMEOUT = (
    os.environ.get("START_CLUSTER_INSTALLATION_TIMEOUT")
    if os.environ.get("START_CLUSTER_INSTALLATION_TIMEOUT") is not None
    else consts.START_CLUSTER_INSTALLATION_TIMEOUT
)
INSTALLING_IN_PROGRESS_TIMEOUT = (
    os.environ.get("INSTALLING_IN_PROGRESS_TIMEOUT")
    if os.environ.get("INSTALLING_IN_PROGRESS_TIMEOUT") is not None
    else consts.INSTALLING_IN_PROGRESS_TIMEOUT
)
